name: Docker Image CI
on:
  push:
    tags:
      - '*.*'    
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Make image name
      run: |
        echo "IMG=${{ secrets.DOCKER_HUB_ORG }}/qterm" >>$GITHUB_ENV
        echo "IMG_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Build and tag Docker image
      run: |
        docker build -t $IMG:latest .
        docker tag $IMG:latest $IMG:${{ github.sha }}
        docker tag $IMG:latest $IMG:$IMG_TAG
    - name: Push Docker image
      run: |
        docker push $IMG:latest
        docker push $IMG:${{ github.sha }}
        docker push $IMG:$IMG_TAG
